apiVersion: v1
kind: Service
metadata:
  name: business-dashboard
spec:
  selector:
    app: business-dashboard
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP

